apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minikube-control-agent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: agent
    spec:
      serviceAccountName: streamsets-agent
      containers:
      - name: sch-control-agent
        image: streamsets/control-agent:latest
        env:
        - name: HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: dpm_agent_master_url
          value: https://kubernetes.default.svc.cluster.local
        - name: dpm_agent_cof_type
          value: "KUBERNETES"
        - name: dpm_agent_dpm_baseurl
          valueFrom:
            configMapKeyRef:
              name: streamsets-config
              key: sch_url
        - name: dpm_agent_component_id
          valueFrom:
            configMapKeyRef:
              name: streamsets-config
              key: agent_id
        - name: dpm_agent_token_string
          valueFrom:
            secretKeyRef:
              name: sch-agent-creds
              key: dpm_agent_token_string
        - name: dpm_agent_name
          value: minikube-control-agent
        - name: dpm_agent_orgId
          valueFrom:
            configMapKeyRef:
              name: streamsets-config
              key: org
        - name: dpm_agent_secret
          value: compsecret
