apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SCH_AGENT_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      serviceAccountName: ${SCH_AGENT_NAME}-serviceaccount
      containers:
      - name: ${SCH_AGENT_NAME}
        image: streamsets/control-agent:${SCH_AGENT_DOCKER_TAG}
        resources:
          requests:
            cpu: "1"
            memory: "2048Mi"
          limits:
            cpu: "2"
            memory: "4096Mi"
        env:
        - name: HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: dpm_agent_master_url
          value: https://kubernetes.default.svc.cluster.local
        - name: dpm_agent_cof_type
          value: "KUBERNETES"
        - name: dpm_agent_dpm_baseurl
          valueFrom:
            configMapKeyRef:
              name: ${SCH_AGENT_NAME}-config
              key: sch_url
        - name: dpm_agent_component_id
          valueFrom:
            configMapKeyRef:
              name: ${SCH_AGENT_NAME}-config
              key: agent_id
        - name: dpm_agent_token_string
          valueFrom:
            secretKeyRef:
              name: ${SCH_AGENT_NAME}-creds
              key: dpm_agent_token_string
        - name: dpm_agent_name
          value: ${SCH_AGENT_NAME}
        - name: dpm_agent_orgId
          valueFrom:
            configMapKeyRef:
              name: ${SCH_AGENT_NAME}-config
              key: org
        - name: dpm_agent_secret
          value: ${SCH_AGENT_NAME}-compsecret
